version: '3'

services:
  multicast:
    build: .
    image: walchko/gunther
    container_name: gunther-container
    hostname: gunther
    # image: octoprint/octoprint
    # container_name: octoprint
    # restart: unless-stopped
    # ports:
    #   - 5000:5000
    # volumes:
    #   - ./tmp:/src
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    # #  - /dev/video0:/dev/video0
    # volumes:
    #   - ./config:/octoprint